name: Docker Release Build
on:
  release:
    types: [published]
jobs:
  push_to_registry:
    name: Build and Push Docker images to GitHub Packages
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - 
        name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}

      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker Build and Push to GitHub Packages
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            docker.pkg.github.com/ralphtro/epcis-event-hash-generator/epcis-hash:latest
            docker.pkg.github.com/ralphtro/epcis-event-hash-generator/epcis-hash:${{ steps.get_version.outputs.VERSION }}
                
      - name: Docker Build and Push to GitHub Packages
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile.webapi
          push: true
          tags: |
            docker.pkg.github.com/ralphtro/epcis-event-hash-generator/webservice:latest
            docker.pkg.github.com/ralphtro/epcis-event-hash-generator/webservice:${{ steps.get_version.outputs.VERSION }}
                    
